// Auto-generated by scripts/promote-content.ts on 2026-05-04T04:51:00.510Z. Do not hand-edit.

import { lesson as lesson_1_1 } from "./topic-1-econ/1.1-basic-economic-concepts/lesson";
import { cards as cards_1_1 } from "./topic-1-econ/1.1-basic-economic-concepts/cards";
import { questions as questions_1_1 } from "./topic-1-econ/1.1-basic-economic-concepts/questions";
import { lesson as lesson_1_2 } from "./topic-1-econ/1.2-financial-reporting/lesson";
import { cards as cards_1_2 } from "./topic-1-econ/1.2-financial-reporting/cards";
import { questions as questions_1_2 } from "./topic-1-econ/1.2-financial-reporting/questions";
import { lesson as lesson_1_3 } from "./topic-1-econ/1.3-analytical-methods/lesson";
import { cards as cards_1_3 } from "./topic-1-econ/1.3-analytical-methods/cards";
import { questions as questions_1_3 } from "./topic-1-econ/1.3-analytical-methods/questions";
import { lesson as lesson_1_4 } from "./topic-1-econ/1.4-types-of-risk/lesson";
import { cards as cards_1_4 } from "./topic-1-econ/1.4-types-of-risk/cards";
import { questions as questions_1_4 } from "./topic-1-econ/1.4-types-of-risk/questions";
import { lesson as lesson_2_1 } from "./topic-2-vehicles/2.1-types-and-characteristics-of-cash-and-cash-equivalents/lesson";
import { cards as cards_2_1 } from "./topic-2-vehicles/2.1-types-and-characteristics-of-cash-and-cash-equivalents/cards";
import { questions as questions_2_1 } from "./topic-2-vehicles/2.1-types-and-characteristics-of-cash-and-cash-equivalents/questions";
import { lesson as lesson_2_2 } from "./topic-2-vehicles/2.2-types-of-fixed-income-securities/lesson";
import { cards as cards_2_2 } from "./topic-2-vehicles/2.2-types-of-fixed-income-securities/cards";
import { questions as questions_2_2 } from "./topic-2-vehicles/2.2-types-of-fixed-income-securities/questions";
import { lesson as lesson_2_3 } from "./topic-2-vehicles/2.3-characteristics-and-valuation-factors-of-fixed-income-securi/lesson";
import { cards as cards_2_3 } from "./topic-2-vehicles/2.3-characteristics-and-valuation-factors-of-fixed-income-securi/cards";
import { questions as questions_2_3 } from "./topic-2-vehicles/2.3-characteristics-and-valuation-factors-of-fixed-income-securi/questions";

export const allContent = {
  lessons: [lesson_1_1, lesson_1_2, lesson_1_3, lesson_1_4, lesson_2_1, lesson_2_2, lesson_2_3],
  cards: [...cards_1_1, ...cards_1_2, ...cards_1_3, ...cards_1_4, ...cards_2_1, ...cards_2_2, ...cards_2_3],
  questions: [...questions_1_1, ...questions_1_2, ...questions_1_3, ...questions_1_4, ...questions_2_1, ...questions_2_2, ...questions_2_3],
};
