import type { Question } from "../../../types/content";

export const questions: Question[] = [
  {
    "stem": "Which U.S. Treasury security has the shortest original maturity and is issued at a discount with no stated coupon?",
    "choices": [
      "Treasury notes",
      "Treasury bonds",
      "Treasury bills",
      "Treasury STRIPS"
    ],
    "answerIndex": 2,
    "rationale": "Treasury bills are issued with maturities of one year or less (4, 8, 13, 17, 26, and 52 weeks) and pay no coupon; the investor's return is the difference between the discounted purchase price and par at maturity. Treasury notes are the top distractor but they are coupon-bearing and have maturities of 2-10 years, so they do not match the 'shortest, no stated coupon' description.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "easy",
    "id": "2f16679ea19b",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "What is the maturity range for U.S. Treasury notes at issuance?",
    "choices": [
      "4 weeks to 1 year",
      "2 to 10 years",
      "10 to 20 years",
      "20 to 30 years"
    ],
    "answerIndex": 1,
    "rationale": "Treasury notes are issued in maturities of 2, 3, 5, 7, and 10 years and pay semiannual interest. The 4-week-to-1-year range describes Treasury bills, which are zero-coupon discount instruments rather than coupon-bearing notes.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "easy",
    "id": "6ea53f35fc9c",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "U.S. Treasury bonds are currently issued with original maturities of:",
    "choices": [
      "1 to 5 years",
      "5 to 10 years",
      "20 and 30 years",
      "40 to 50 years"
    ],
    "answerIndex": 2,
    "rationale": "T-bonds are long-dated coupon securities issued at 20 and 30 years. The 5-to-10-year option overlaps with Treasury notes and is therefore the most common wrong pick, but 10-year instruments are notes, not bonds.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "easy",
    "id": "b5378e6d7198",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Treasury Inflation-Protected Securities (TIPS) protect investors against inflation primarily by adjusting which feature?",
    "choices": [
      "The coupon rate",
      "The principal value",
      "The maturity date",
      "The yield to maturity"
    ],
    "answerIndex": 1,
    "rationale": "On TIPS the stated coupon rate is fixed, but the principal is indexed to the non-seasonally-adjusted CPI-U, so each semiannual interest payment changes because it is computed on the inflation-adjusted principal. Investors who think the coupon rate adjusts confuse the mechanism: the rate is fixed, the base on which it is applied moves.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "easy",
    "id": "9bab3ff7de1e",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A general obligation (GO) municipal bond is backed primarily by:",
    "choices": [
      "Revenues from a specific project such as a toll road",
      "The full faith, credit, and taxing power of the issuing municipality",
      "A federal guarantee from the U.S. Treasury",
      "Reserves held by a private bond insurer"
    ],
    "answerIndex": 1,
    "rationale": "GO bonds are unsecured obligations backed by the issuer's full faith, credit, and ad valorem taxing power. Revenue bonds, the leading distractor, are paid only from the cash flows of a specific facility or enterprise and do not have recourse to the issuer's general taxing power.",
    "citation": {
      "source": "OTHER",
      "ref": "MSRB"
    },
    "difficulty": "easy",
    "id": "6e706e598ab2",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which type of municipal bond is repaid solely from the cash flows generated by the financed project, such as a stadium or water utility?",
    "choices": [
      "General obligation bond",
      "Revenue bond",
      "Tax anticipation note",
      "Build America Bond"
    ],
    "answerIndex": 1,
    "rationale": "Revenue bonds are self-supporting debt secured only by user fees, tolls, or other project-specific receipts. GO bonds are the top distractor, but they are backed by the issuer's taxing power rather than dedicated project revenues.",
    "citation": {
      "source": "OTHER",
      "ref": "MSRB"
    },
    "difficulty": "easy",
    "id": "9f5c7c96fb07",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Interest from a typical state or local municipal bond is generally:",
    "choices": [
      "Subject to federal, state, and local income tax",
      "Subject to federal income tax but exempt from state tax",
      "Exempt from federal income tax",
      "Taxable as a long-term capital gain"
    ],
    "answerIndex": 2,
    "rationale": "Interest on most municipal bonds is exempt from federal income tax under the Internal Revenue Code, which is the principal reason munis trade at lower yields than comparable taxable bonds. The 'fully taxable' option describes corporate bonds and is the most common confusion.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "easy",
    "id": "ccd840fed7a1",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "In a corporate bankruptcy, holders of senior unsecured corporate bonds rank where in the capital structure?",
    "choices": [
      "Behind preferred stockholders but ahead of common stockholders",
      "Ahead of secured creditors",
      "Ahead of preferred and common stockholders but behind secured creditors",
      "Equal to common stockholders"
    ],
    "answerIndex": 2,
    "rationale": "The standard liquidation priority is secured creditors, then unsecured creditors (including senior unsecured bondholders), then preferred shareholders, then common shareholders. Putting bondholders 'ahead of secured creditors' inverts this — secured bondholders have a specific lien on collateral and outrank unsecured bondholders.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "easy",
    "id": "ef472bde307d",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "An asset-backed security (ABS) is best described as a debt instrument:",
    "choices": [
      "Issued directly by the U.S. Treasury",
      "Backed by a pool of underlying receivables such as auto loans or credit-card balances",
      "Whose interest is exempt from federal income tax",
      "That pays no principal until final maturity"
    ],
    "answerIndex": 1,
    "rationale": "ABS are created when an issuer pools financial assets — auto loans, credit-card receivables, student loans, equipment leases — and sells claims on the pooled cash flows to investors via a special-purpose vehicle. The 'no principal until maturity' option describes a balloon or zero-coupon structure and ignores the pass-through nature typical of ABS.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "easy",
    "id": "1f8469c9cc67",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which statement about U.S. Treasury securities is correct?",
    "choices": [
      "They are subject to significant credit (default) risk.",
      "They are backed by the full faith and credit of the U.S. government.",
      "They are insured by the FDIC up to $250,000.",
      "They are exempt from federal income tax."
    ],
    "answerIndex": 1,
    "rationale": "Treasuries carry the full faith and credit of the U.S. government and are treated as the benchmark risk-free asset for U.S. dollar investors. The FDIC option is wrong because FDIC insures bank deposits, not Treasury securities — Treasuries don't need that insurance because the issuer is the federal government itself.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "easy",
    "id": "aebde7436a88",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A bond issued by the government of a country other than the United States is referred to as:",
    "choices": [
      "A corporate bond",
      "A municipal bond",
      "Sovereign debt",
      "An asset-backed security"
    ],
    "answerIndex": 2,
    "rationale": "Debt issued by a national government other than the U.S. is termed sovereign debt; quality varies widely with the issuing country's economic and political stability. 'Corporate bond' is wrong because corporate debt is issued by private companies, not governments.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "easy",
    "id": "a7460a5f8c3b",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "TIPS principal is adjusted based on changes in which index?",
    "choices": [
      "The Producer Price Index (PPI)",
      "The non-seasonally-adjusted Consumer Price Index for All Urban Consumers (CPI-U)",
      "The S&P 500 Index",
      "The Federal Funds Rate"
    ],
    "answerIndex": 1,
    "rationale": "TIPS principal is indexed semi-annually to CPI-U (non-seasonally-adjusted), and the fixed coupon is then applied to the inflation-adjusted principal. The PPI is a producer-side measure that does not drive Treasury inflation accrual; that's why CPI-U, not PPI, is the relevant index.",
    "citation": {
      "source": "OTHER",
      "ref": "Bureau of Labor Statistics"
    },
    "difficulty": "medium",
    "id": "537ae2ddaca2",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which feature most clearly distinguishes a general obligation bond from a revenue bond?",
    "choices": [
      "GO bonds are taxable while revenue bonds are tax-exempt",
      "GO bonds are repaid from ad valorem taxes while revenue bonds are repaid from project-specific receipts",
      "GO bonds always carry shorter maturities than revenue bonds",
      "GO bonds are issued only by the federal government"
    ],
    "answerIndex": 1,
    "rationale": "GO bonds are serviced by the issuer's general taxing power (often property/ad valorem taxes), whereas revenue bonds are paid solely from a designated revenue stream such as tolls, water fees, or stadium revenues. The 'taxability' distractor is wrong: both can be federally tax-exempt municipal securities.",
    "citation": {
      "source": "OTHER",
      "ref": "MSRB"
    },
    "difficulty": "medium",
    "id": "f1d62973a551",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which ratio is most commonly used to evaluate the credit quality of a revenue bond?",
    "choices": [
      "Debt-to-equity ratio",
      "Price-to-earnings ratio",
      "Debt service coverage ratio",
      "Current ratio"
    ],
    "answerIndex": 2,
    "rationale": "The debt service coverage ratio measures pledged net project revenues against required principal and interest payments — a 1.5x or 2.0x covenant is common. P/E ratio is the leading distractor but applies to equity valuation, not revenue-bond credit analysis.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "e396bd32bca5",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "An 'insured' municipal bond carries:",
    "choices": [
      "FDIC insurance up to $250,000",
      "A guarantee of timely principal and interest from a private monoline bond insurer",
      "An SIPC guarantee against issuer default",
      "A guarantee from the U.S. Treasury"
    ],
    "answerIndex": 1,
    "rationale": "An insured muni has its principal and interest guaranteed by a private bond insurer (e.g., AGM, BAM), which historically allowed it to inherit the insurer's credit rating. SIPC is wrong because SIPC protects customer assets when broker-dealers fail, not municipal issuer credit.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "132fda8541c2",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "An investor who lives in California and buys a California state-issued municipal bond typically receives interest that is:",
    "choices": [
      "Taxed federally and at the state level",
      "Exempt from federal tax but taxed by California",
      "Exempt from both federal and California state income tax (double exempt)",
      "Subject to a 28% federal alternative tax only"
    ],
    "answerIndex": 2,
    "rationale": "Most states exempt their own municipal bond interest from state income tax, and federal law generally exempts municipal interest from federal tax — producing 'double exemption' for in-state investors. The 'taxed by California' choice ignores the long-standing in-state exemption that drives much of the home-state demand for munis.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "medium",
    "id": "85fee5bf8569",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Bonds issued by a U.S. territory such as Puerto Rico are commonly described as 'triple tax-exempt' for U.S. investors because their interest is generally exempt from:",
    "choices": [
      "Federal income tax, corporate tax, and capital gains tax",
      "Federal, state, and local income tax for residents of any U.S. state",
      "FICA, Medicare, and federal unemployment tax",
      "AMT, federal, and estate tax"
    ],
    "answerIndex": 1,
    "rationale": "Under federal law, interest on bonds issued by U.S. territories like Puerto Rico, Guam, and the U.S. Virgin Islands is exempt from federal, state, and local income tax for any U.S. investor — hence 'triple tax-exempt.' The 'corporate/capital gains' option confuses different taxes that are not relevant to interest income classification.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "medium",
    "id": "55dc206546f2",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which firms are the three principal nationally recognized statistical rating organizations (NRSROs) used to rate corporate bonds?",
    "choices": [
      "S&P, Moody's, and Fitch",
      "FINRA, MSRB, and SIPC",
      "Bloomberg, Reuters, and Morningstar",
      "PCAOB, AICPA, and FASB"
    ],
    "answerIndex": 0,
    "rationale": "S&P Global, Moody's, and Fitch dominate corporate-bond ratings and are the NRSROs an exam typically references. FINRA/MSRB/SIPC are self-regulators or insurers, not rating agencies, which is why that distractor is wrong.",
    "citation": {
      "source": "OTHER",
      "ref": "S&P Global Ratings"
    },
    "difficulty": "medium",
    "id": "8504f9d57774",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A corporate bond is generally considered 'investment grade' when its credit rating is at least:",
    "choices": [
      "AAA / Aaa",
      "BBB- / Baa3",
      "BB+ / Ba1",
      "C / Ca"
    ],
    "answerIndex": 1,
    "rationale": "Investment grade begins at BBB- (S&P/Fitch) or Baa3 (Moody's); ratings below that are speculative grade or 'junk.' BB+ / Ba1 is the leading distractor because it is one notch below the cutoff — and that single notch is precisely the line that triggers different regulatory and institutional treatment.",
    "citation": {
      "source": "OTHER",
      "ref": "Moody's Investors Service"
    },
    "difficulty": "medium",
    "id": "e6abe5ec9b64",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Treasury STRIPS are best described as:",
    "choices": [
      "Coupon-bearing Treasury securities sold only to foreign buyers",
      "Zero-coupon Treasury obligations created by separating the principal and interest payments of Treasury notes and bonds",
      "Inflation-adjusted Treasury bonds",
      "Short-term Treasury bills with floating rates"
    ],
    "answerIndex": 1,
    "rationale": "Under the STRIPS (Separate Trading of Registered Interest and Principal of Securities) program, primary dealers strip a coupon-bearing Treasury into individual zero-coupon pieces that are sold at a discount and pay par at maturity. Calling them inflation-adjusted is wrong — that's TIPS, an entirely different program.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "medium",
    "id": "23a634cb8304",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A material risk that is generally more pronounced for asset-backed securities than for plain-vanilla Treasury bonds is:",
    "choices": [
      "Sovereign default risk",
      "Prepayment (and extension) risk on the underlying loans",
      "Foreign currency risk",
      "Risk of a U.S. government shutdown"
    ],
    "answerIndex": 1,
    "rationale": "ABS cash flows depend on borrower behavior, so when underlying borrowers prepay faster than expected (in falling rates) or slower than expected (in rising rates), the timing of ABS cash flows becomes uncertain — prepayment/extension risk. Sovereign risk is irrelevant for U.S.-domiciled ABS because no foreign government is the obligor.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "94a2da3b479f",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A mortgage-backed security (MBS) is best characterized as:",
    "choices": [
      "A type of municipal revenue bond",
      "A specific subset of asset-backed security collateralized by residential or commercial mortgage loans",
      "A federal Treasury issuance",
      "A certificate of deposit issued by a savings institution"
    ],
    "answerIndex": 1,
    "rationale": "MBS are a subset of ABS where the underlying receivables are mortgage loans, often pooled and guaranteed by agencies such as Ginnie Mae, Fannie Mae, or Freddie Mac. Calling MBS a Treasury issuance is wrong because the U.S. Treasury does not issue MBS — agencies and private issuers do.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "7f7f8cc6c7a6",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Interest income earned on direct U.S. Treasury obligations is:",
    "choices": [
      "Subject to federal, state, and local income tax",
      "Subject to federal income tax but exempt from state and local income tax",
      "Exempt from federal income tax",
      "Subject to FICA and Medicare withholding"
    ],
    "answerIndex": 1,
    "rationale": "Federal law exempts interest on direct Treasury obligations from state and local income taxation, but the income is fully taxable at the federal level. Confusing this with municipal bond treatment (federally exempt) is the classic error — Treasuries are the mirror image of munis.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "medium",
    "id": "35d4ade64c1b",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A bond issued in the United States, denominated in U.S. dollars, by a foreign corporation or government is called:",
    "choices": [
      "A Eurobond",
      "A Yankee bond",
      "A Brady bond",
      "A Samurai bond"
    ],
    "answerIndex": 1,
    "rationale": "Yankee bonds are dollar-denominated bonds issued in the U.S. by non-U.S. issuers and are registered with the SEC. Eurobonds — the top distractor — are issued in a currency different from that of the country where they are sold and are typically not SEC-registered, so they are not the same instrument.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "108f38b622c7",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which statement best describes a Eurobond?",
    "choices": [
      "A bond denominated in euros that may only be sold within the European Union",
      "A long-term debt instrument denominated in a currency other than the currency of the country in which it is issued",
      "A short-term obligation issued by the European Central Bank",
      "A bond issued by a U.S. corporation but settled exclusively in euros"
    ],
    "answerIndex": 1,
    "rationale": "A Eurobond is defined by the mismatch between its currency of denomination and its country of issuance — for example, a yen-denominated bond sold in London. The 'denominated in euros' option confuses the prefix 'Euro-' with the euro currency, which is a common but incorrect inference.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "808c518279f5",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Brady bonds were created primarily to:",
    "choices": [
      "Refinance defaulted emerging-market sovereign loans into tradable, partially collateralized U.S. dollar bonds",
      "Fund the U.S. federal deficit during World War II",
      "Provide tax-free retirement income to U.S. veterans",
      "Insure municipal bonds against default"
    ],
    "answerIndex": 0,
    "rationale": "Brady bonds (named for U.S. Treasury Secretary Nicholas Brady) restructured commercial-bank loans to developing countries into U.S. dollar bonds, often partially collateralized by zero-coupon Treasuries. They are unrelated to U.S. wartime financing, which is the leading historical distractor but a separate program (war bonds).",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "medium",
    "id": "59f439b5f57e",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A zero-coupon bond is most accurately described as a debt security that:",
    "choices": [
      "Pays a higher coupon than comparable bonds",
      "Pays no periodic interest and is sold at a deep discount to par",
      "Floats its coupon based on prevailing short-term rates",
      "Adjusts its principal to inflation"
    ],
    "answerIndex": 1,
    "rationale": "A zero-coupon bond pays no current interest; the investor's return is the difference between purchase price and par at maturity. The inflation-adjusted-principal description fits TIPS, not zero-coupons, so that distractor is wrong.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "a3bec0b6ac84",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "An investor in an emerging-market sovereign bond denominated in the local currency of the issuing country faces all of the following risks; which one is most directly tied to the issuing country's macroeconomic management?",
    "choices": [
      "Reinvestment risk",
      "Currency / sovereign risk reflecting devaluation or default by the foreign government",
      "Liquidity risk in the U.S. corporate bond market",
      "Prepayment risk from underlying mortgages"
    ],
    "answerIndex": 1,
    "rationale": "Emerging-market sovereign bonds expose the holder to the credit and currency policies of a foreign government, including potential devaluation, capital controls, or outright default. Prepayment risk is unrelated because there are no underlying mortgages in a sovereign bond.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "medium",
    "id": "54a0b95ee08d",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "An investor's marginal federal tax bracket is 32%. To match a 3.40% yield on a federally tax-exempt municipal bond, what must a comparable taxable corporate bond yield (ignoring state taxes)?",
    "choices": [
      "Approximately 4.50%",
      "Approximately 5.00%",
      "Approximately 3.40%",
      "Approximately 2.31%"
    ],
    "answerIndex": 1,
    "rationale": "Tax-equivalent yield = tax-free yield / (1 - marginal rate) = 0.0340 / (1 - 0.32) = 0.0340 / 0.68 ≈ 5.00%. The 4.50% distractor uses a 24% bracket rather than 32%, a common arithmetic error when test-takers misread the tax rate.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "hard",
    "id": "5ba63c8d95f6",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Each year a TIPS principal is adjusted upward for inflation, the inflation accretion is:",
    "choices": [
      "Tax-free at all levels of government",
      "Taxed at the federal level in the year accrued, even though the cash isn't received until maturity ('phantom income')",
      "Treated as a long-term capital gain only at sale",
      "Subject only to state income tax"
    ],
    "answerIndex": 1,
    "rationale": "The annual upward inflation adjustment to TIPS principal is reportable as ordinary income in the year it accrues — investors owe federal tax on income they have not yet received in cash, which is why TIPS are most commonly held in tax-deferred accounts. Treating the accretion as a capital gain at sale ignores the annual recognition rule under the OID/inflation-accrual provisions of the Internal Revenue Code.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "hard",
    "id": "7d5a2ad72cdf",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which factor is most likely to cause a general obligation (GO) bond to default before a comparably rated revenue bond from the same issuer?",
    "choices": [
      "A sharp decline in the issuer's tax base, since GO bonds depend on general taxing power",
      "A decline in toll revenues, since GO bonds are paid from project tolls",
      "A change in federal tax rates, since GO bonds lose their exemption first",
      "GO bonds typically default before revenue bonds because they are unsecured equity claims"
    ],
    "answerIndex": 0,
    "rationale": "GO bonds are serviced from the issuer's general fund and ad valorem taxing capacity, so a deteriorating tax base directly threatens repayment. Toll revenues affect revenue bonds (the top distractor), not GO bonds, which makes that choice incorrect.",
    "citation": {
      "source": "OTHER",
      "ref": "MSRB"
    },
    "difficulty": "hard",
    "id": "8423f051cfdb",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Build America Bonds (BABs), authorized under the American Recovery and Reinvestment Act of 2009, are best described as:",
    "choices": [
      "Federally tax-exempt municipal bonds with no investor benefit beyond tax exemption",
      "Taxable municipal bonds, where the issuer or investor receives a federal subsidy or credit",
      "Federal Treasury obligations earmarked for infrastructure",
      "FDIC-insured corporate bonds"
    ],
    "answerIndex": 1,
    "rationale": "BABs are taxable to the investor at the federal level; in exchange, the program provided issuers a direct federal interest-cost subsidy (or, in another variant, gave investors a federal tax credit). Treating BABs as ordinary tax-exempt munis misses the entire purpose of the program — broadening the buyer base by making them taxable.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "hard",
    "id": "56c720ce6079",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Which statement about TIPS coupon mechanics is correct?",
    "choices": [
      "Both the coupon rate and the principal are adjusted based on CPI",
      "The coupon rate is fixed, but each interest payment varies because the rate is applied to an inflation-adjusted principal",
      "Coupon payments are fixed in dollar terms regardless of inflation",
      "Coupons are paid only at maturity"
    ],
    "answerIndex": 1,
    "rationale": "The TIPS coupon rate is set at auction and never changes; semiannual interest, however, equals that fixed rate applied to the inflation-adjusted principal, so the dollar amount of each payment moves with CPI. The 'fixed dollar' option ignores the principal adjustment that is the entire point of TIPS.",
    "citation": {
      "source": "OTHER",
      "ref": "U.S. Treasury"
    },
    "difficulty": "hard",
    "id": "dccb9e19324a",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "A U.S. retail investor who buys a euro-denominated bond issued by a German corporation faces an additional risk that a comparable USD-denominated U.S. corporate bondholder does not bear. Which is it?",
    "choices": [
      "Credit risk of the issuer",
      "Foreign exchange (currency) risk",
      "Reinvestment risk",
      "Federal income tax on coupon payments"
    ],
    "answerIndex": 1,
    "rationale": "Coupon and principal repayments will be received in euros, so depreciation of the euro versus the dollar reduces the dollar value of those cash flows for a U.S. investor. Credit risk exists in both cases, so it is not the additional risk that distinguishes the foreign-currency bond.",
    "citation": {
      "source": "OTHER",
      "ref": "Standard finance textbook"
    },
    "difficulty": "hard",
    "id": "3ec2c6bea12b",
    "subtopicId": "2.2",
    "reviewed": false
  },
  {
    "stem": "Original Issue Discount (OID) on a corporate bond purchased at issuance is generally treated for federal income tax purposes as:",
    "choices": [
      "A long-term capital gain recognized only at maturity",
      "Ordinary interest income that accrues and is taxed each year over the life of the bond",
      "Tax-free income because no cash is received before maturity",
      "Subject only to state income tax"
    ],
    "answerIndex": 1,
    "rationale": "OID is treated as interest income that accretes annually under the constant-yield method, so the holder reports phantom interest income each year even without receiving cash payments. Treating OID as a capital gain at maturity misstates the timing rule and is the classic exam trap.",
    "citation": {
      "source": "OTHER",
      "ref": "IRS Publication 550"
    },
    "difficulty": "hard",
    "id": "e6a51c5e2e4b",
    "subtopicId": "2.2",
    "reviewed": false
  }
];
