// Auto-runnable via `npx tsx scripts/promote-content.ts`.
// Uses only Node built-ins: node:fs, node:path, node:util, node:child_process.

import * as fs from "node:fs";
import * as path from "node:path";
import { parseArgs } from "node:util";
import { spawnSync } from "node:child_process";

const USAGE = `Usage: npx tsx scripts/promote-content.ts [options]

Options:
  --from <path>   Source dir (default: scripts/out)
  --to <path>     Destination dir (default: src/content)
  --dry-run       Preview without writing anything
  --keep-stub     Don't delete src/content/sample/ after promotion
  --fix-existing  Don't move anything; instead scan <to> for stale
                  ../../../src/types/content imports left by an older
                  generator and rewrite them to ../../../types/content.
  --help          Show this message and exit 2
`;

const out = (s: string) => process.stdout.write(s + "\n");
const err = (s: string) => process.stderr.write(s + "\n");

function isDir(p: string): boolean {
  try { return fs.statSync(p).isDirectory(); } catch { return false; }
}

/**
 * Rewrite stale type-import paths inside a freshly-moved subtopic dir.
 * Earlier generator runs hard-coded `../../../src/types/content` — that path
 * was correct from `scripts/out/<topic>/<subtopic>/`'s 4-level depth but wrong
 * once the file lives at `src/content/<topic>/<subtopic>/`'s 3-level depth.
 * From the destination the path is `../../../types/content`. Rewrite both
 * the bad and any legacy variants so older `scripts/out/` artifacts move
 * cleanly.
 */
function rewriteImportsIn(dir: string): void {
  for (const f of ["lesson.ts", "cards.ts", "questions.ts"]) {
    const fp = path.join(dir, f);
    if (!fs.existsSync(fp)) continue;
    const before = fs.readFileSync(fp, "utf8");
    const after = before
      .replace(/from\s+["']\.\.\/\.\.\/\.\.\/src\/types\/content["']/g, 'from "../../../types/content"')
      .replace(/from\s+["']\.\.\/\.\.\/\.\.\/\.\.\/src\/types\/content["']/g, 'from "../../../types/content"');
    if (after !== before) fs.writeFileSync(fp, after, "utf8");
  }
}

/** Walk an entire content tree (e.g., src/content/) and rewrite any stale
 * imports left behind by a previous promotion run. */
function fixExistingImports(root: string): number {
  let fixed = 0;
  if (!isDir(root)) return 0;
  for (const topicSlug of fs.readdirSync(root)) {
    const topicPath = path.join(root, topicSlug);
    if (!isDir(topicPath)) continue;
    for (const subtopicDir of fs.readdirSync(topicPath)) {
      const subPath = path.join(topicPath, subtopicDir);
      if (!isDir(subPath)) continue;
      for (const f of ["lesson.ts", "cards.ts", "questions.ts"]) {
        const fp = path.join(subPath, f);
        if (!fs.existsSync(fp)) continue;
        const before = fs.readFileSync(fp, "utf8");
        const after = before
          .replace(/from\s+["']\.\.\/\.\.\/\.\.\/src\/types\/content["']/g, 'from "../../../types/content"')
          .replace(/from\s+["']\.\.\/\.\.\/\.\.\/\.\.\/src\/types\/content["']/g, 'from "../../../types/content"');
        if (after !== before) {
          fs.writeFileSync(fp, after, "utf8");
          fixed += 1;
        }
      }
    }
  }
  return fixed;
}

interface Sub { topicSlug: string; subtopicDir: string; subtopicId: string }

function findSubtopics(dir: string): Sub[] {
  const result: Sub[] = [];
  if (!isDir(dir)) return result;
  for (const topicSlug of fs.readdirSync(dir)) {
    const topicPath = path.join(dir, topicSlug);
    if (!isDir(topicPath)) continue;
    for (const subtopicDir of fs.readdirSync(topicPath)) {
      const subPath = path.join(topicPath, subtopicDir);
      if (!isDir(subPath)) continue;
      const required = ["lesson.ts", "cards.ts", "questions.ts", "manifest.json"];
      if (!required.every((f) => fs.existsSync(path.join(subPath, f)))) continue;
      const m = subtopicDir.match(/^(\d+\.\d+)/);
      result.push({ topicSlug, subtopicDir, subtopicId: m ? m[1] : subtopicDir });
    }
  }
  return result;
}

function buildIndex(subs: Sub[], stubDir: string, keepStub: boolean, timestamp: string): string {
  subs.sort((a, b) => a.subtopicId.localeCompare(b.subtopicId));
  const lines = [`// Auto-generated by scripts/promote-content.ts on ${timestamp}. Do not hand-edit.`, ""];
  if (keepStub && isDir(stubDir))
    lines.push(`import { sampleLesson, sampleCards, sampleQuestions } from "./sample/1.1-sample";`);
  for (const { topicSlug, subtopicDir, subtopicId } of subs) {
    const s = subtopicId.replace(/\./g, "_"), base = `./${topicSlug}/${subtopicDir}`;
    lines.push(`import { lesson as lesson_${s} } from "${base}/lesson";`);
    lines.push(`import { cards as cards_${s} } from "${base}/cards";`);
    lines.push(`import { questions as questions_${s} } from "${base}/questions";`);
  }
  lines.push("");
  lines.push("export const allContent = {");
  const ids = subs.map((s) => s.subtopicId.replace(/\./g, "_"));
  const lessons = ids.map((i) => `lesson_${i}`);
  const cards   = ids.map((i) => `...cards_${i}`);
  const qs      = ids.map((i) => `...questions_${i}`);
  if (keepStub && isDir(stubDir)) { lessons.push("sampleLesson"); cards.push("...sampleCards"); qs.push("...sampleQuestions"); }
  lines.push(`  lessons: [${lessons.join(", ")}],`);
  lines.push(`  cards: [${cards.join(", ")}],`);
  lines.push(`  questions: [${qs.join(", ")}],`);
  lines.push("};", "");
  return lines.join("\n");
}

function main(argv: string[]): number {
  let parsed;
  try {
    parsed = parseArgs({
      args: argv,
      options: {
        "dry-run":      { type: "boolean", default: false },
        from:           { type: "string",  default: "scripts/out" },
        to:             { type: "string",  default: "src/content" },
        "keep-stub":    { type: "boolean", default: false },
        "fix-existing": { type: "boolean", default: false },
        help:           { type: "boolean", default: false },
      },
      allowPositionals: false, strict: true,
    });
  } catch (e) { err((e as Error).message); err(USAGE); return 2; }

  const v = parsed.values as {
    "dry-run": boolean; from: string; to: string;
    "keep-stub": boolean; "fix-existing": boolean; help: boolean;
  };
  if (v.help) { out(USAGE); return 2; }

  const fromDir  = path.resolve(v.from);
  const toDir    = path.resolve(v.to);
  const dryRun   = v["dry-run"];
  const keepStub = v["keep-stub"];
  const timestamp = new Date().toISOString();

  // One-shot repair path: scan an existing src/content/ tree and rewrite
  // stale `../../../src/types/content` imports to the correct
  // `../../../types/content`. Useful after a generation run that pre-dates
  // the import-path fix.
  if (v["fix-existing"]) {
    if (dryRun) {
      out(`[dry-run] would scan ${toDir} for stale imports`);
      return 0;
    }
    const fixed = fixExistingImports(toDir);
    out(`Rewrote ${fixed} file(s) under ${toDir}.`);
    return 0;
  }

  // ── prerequisites ────────────────────────────────────────────────────────
  if (!isDir(fromDir)) {
    err(`Error: --from path does not exist or is not a directory: ${fromDir}`);
    return 1;
  }
  const subtopics = findSubtopics(fromDir);
  if (subtopics.length === 0) {
    err(`Error: no valid subtopic dirs found under ${fromDir}.`);
    err(`Expected: <from>/<topic-slug>/<subtopic-dir>/{lesson.ts,cards.ts,questions.ts,manifest.json}`);
    return 1;
  }

  // ── move subtopics ───────────────────────────────────────────────────────
  const topicSet = new Set(subtopics.map((s) => s.topicSlug));
  let movedCount = 0;

  for (const { topicSlug, subtopicDir } of subtopics) {
    const src = path.join(fromDir, topicSlug, subtopicDir);
    const dst = path.join(toDir,   topicSlug, subtopicDir);
    if (dryRun) { out(`[dry-run] MOVE ${src} → ${dst}`); continue; }
    if (isDir(dst)) { out(`SKIP (already exists): ${dst}`); continue; }
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.cpSync(src, dst, { recursive: true });
    fs.rmSync(src, { recursive: true });
    rewriteImportsIn(dst);
    out(`MOVED: ${src} → ${dst}`);
    movedCount++;
  }

  // ── stub deletion ────────────────────────────────────────────────────────
  const stubDir = path.join(toDir, "sample");
  const hasReal1 = subtopics.some(({ topicSlug, subtopicId }) => topicSlug.startsWith("topic-1") && subtopicId.startsWith("1."));
  let stubStatus = "not present";

  if (hasReal1 && isDir(stubDir)) {
    if (dryRun) {
      out(`[dry-run] ${keepStub ? "KEEP (--keep-stub)" : "DELETE"} stub: ${stubDir}`);
      stubStatus = keepStub ? "kept (--keep-stub)" : "would delete";
    } else if (keepStub) {
      err(`Warning: --keep-stub set but src/content/sample/ has subtopicId "1.1" which collides with promoted content. loadContent() will load both.`);
      stubStatus = "kept (--keep-stub)";
    } else {
      fs.rmSync(stubDir, { recursive: true });
      out(`DELETED stub: ${stubDir}`);
      stubStatus = "deleted";
    }
  }

  // ── regenerate index.ts ──────────────────────────────────────────────────
  const indexPath = path.join(toDir, "index.ts");
  // For dry-run: build preview using from-dir subtopics mapped to their to-dir paths
  const indexSubs = dryRun ? subtopics : findSubtopics(toDir);
  const indexContent = buildIndex(indexSubs, stubDir, keepStub, timestamp);

  if (dryRun) {
    out(`[dry-run] WRITE ${indexPath}:`);
    out(indexContent);
  } else {
    fs.writeFileSync(indexPath, indexContent, "utf8");
    out(`WROTE: ${indexPath}`);
  }

  // ── TypeScript sanity check ──────────────────────────────────────────────
  let tsStatus = "skipped (dry-run)";
  if (!dryRun) {
    const tsc = spawnSync("npx", ["tsc", "--noEmit", "-p", "tsconfig.json"],
      { encoding: "utf8", cwd: path.resolve(".") });
    if (tsc.status === 0) {
      tsStatus = "OK";
    } else {
      tsStatus = "see errors above";
      if (tsc.stdout) out(tsc.stdout);
      if (tsc.stderr) err(tsc.stderr);
    }
  }

  // ── summary ──────────────────────────────────────────────────────────────
  out("");
  out(`Promoted ${subtopics.length} subtopics across ${topicSet.size} topics.`);
  out(`src/content/index.ts: ${subtopics.length * 3} items aggregated.`);
  out(`Stub: ${stubStatus}.`);
  out(`TypeScript: ${tsStatus}.`);
  out(`Next: npm test && npm run build to verify the app still loads.`);

  return 0;
}

const invoked = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (invoked.endsWith("promote-content.ts")) {
  process.exit(main(process.argv.slice(2)));
}
